require 'temple'
require 'tilt'

require 'slaml/parser'
require 'slaml/filter'
require 'slaml/end_inserter'
require 'slaml/control_structures'
require 'slaml/engine'
require 'slaml/template'
require 'slaml/version'
